name: Release
on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Type of version bump"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install aqua
        uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.43.1

      - name: Version
        run: just bump-and-commit-version ${{ github.event.inputs.version_type }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Release
        run: just release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
